// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvyhtqorymmbbjtsppab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2eWh0cW9yeW1tYmJqdHNwcGFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTcyMjYsImV4cCI6MjA2NTQ5MzIyNn0.huPWlwwSkXBd12tk8ZBNrk_5FtNeunoVs1ddWdGBCnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);